### PR TITLE
bump dependencies

### PR DESCRIPTION
**Pull request by jqnatividad**

### CODE REVIEW

**Comment by kindly** [comment]
@jqnatividad completely missed this pull request. I have just published version 0.8.8 with all the latest deps.  This includes the latest duckdb which now compiles quicker and uses less memory!

**Comment by jqnatividad** [comment]
Thanks @kindly! Just in time for 0.116.0 too!

Hopefully, the benchmarks for `to` show an improvement as well!

https://qsv.dathere.com/benchmarks

**Comment by jqnatividad** [comment]
BTW @kindly, just out of curiosity, which of the `to` subcommands require duckdb?

Just wondering as I'd like to cut down on the binary size of qsv itself and was thinking of gating those subcommands behind a feature.

**Comment by kindly** [comment]
@jqnatividad just `parquet` requires duckdb. There is a feature flag already to disable duckdb and parquet files here:

https://github.com/kindly/csvs_convert/blob/main/Cargo.toml#L52

**Pull request closed without merging**
